packages:
  - "."
  - "api-spec"
allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
overrides:
  '@typespec/compiler@<=1.15.0': ^1.16.0-dev.0
  '@typespec/openapi3@<=1.15.0': ^1.16.0-dev.0
