packages:
  - '.'
  - 'api-spec'
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - '@angular/cdk@22.1.6'
overrides:
  '@typespec/compiler@<=1.15.0': ^1.16.0-dev.0
  '@typespec/openapi3@<=1.15.0': ^1.16.0-dev.0
