/**
 * Generated from `src/styles/tokens/_tokens.scss` by `scripts/generate-tokens.mjs`.
 * Committed, never hand-edited (ADR 0007). Consumed only by `DesignTokenService`,
 * which applies each entry as a `--`-prefixed CSS custom property at bootstrap.
 */
export const DESIGN_TOKENS = {
  'color-surface': '#ffffff',
  'color-surface-raised': '#ffffff',
  'color-surface-sunken': '#f4f5f7',
  'color-surface-hover': '#eceef1',
  'color-ink': '#14181f',
  'color-ink-muted': '#4a5260',
  'color-ink-inverted': '#ffffff',
  'color-border': '#d7dbe0',
  'color-border-strong': '#6b7480',
  'color-accent': '#1f5fbf',
  'color-accent-hover': '#174993',
  'color-accent-subtle': '#e8f0fc',
  'color-danger': '#b3261e',
  'color-danger-hover': '#8c1d17',
  'color-danger-subtle': '#fdecea',
  'color-success': '#1a6b3c',
  'color-warning': '#8a5300',
  'color-focus-ring': '#1f5fbf',
  'color-scrim': 'rgba(15, 20, 28, 0.55)',
  'color-tracker-1': '#1f5fbf',
  'color-tracker-2': '#7a3ea3',
  'color-tracker-3': '#b3261e',
  'color-tracker-4': '#8a5300',
  'color-tracker-5': '#1a6b3c',
  'color-tracker-6': '#0f6b78',
  'color-tracker-7': '#a02b62',
  'color-tracker-8': '#4a5260',
  'space-0': '0',
  'space-1': '2px',
  'space-2': '4px',
  'space-3': '8px',
  'space-4': '12px',
  'space-5': '16px',
  'space-6': '24px',
  'space-7': '32px',
  'space-8': '48px',
  'font-sans': "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
  'font-mono': "ui-monospace, 'SFMono-Regular', Menlo, monospace",
  'text-xs': '12px',
  'text-sm': '14px',
  'text-md': '16px',
  'text-lg': '20px',
  'text-xl': '25px',
  'text-2xl': '31px',
  'leading-tight': '1.25',
  'leading-normal': '1.5',
  'weight-regular': '400',
  'weight-medium': '500',
  'weight-bold': '700',
  'radius-sm': '3px',
  'radius-md': '6px',
  'radius-lg': '12px',
  'radius-full': '999px',
  'shadow-sm': '0 1px 2px rgba(15, 20, 28, 0.08)',
  'shadow-md': '0 4px 12px rgba(15, 20, 28, 0.12)',
  'shadow-lg': '0 12px 32px rgba(15, 20, 28, 0.18)',
  'z-base': '0',
  'z-sticky': '100',
  'z-overlay': '200',
  'z-dialog': '300',
  'z-toast': '400',
  'motion-fast': '120ms',
  'motion-normal': '200ms',
  'motion-slow': '320ms',
  'ease-standard': 'cubic-bezier(0.2, 0, 0, 1)',
  'control-height': '36px',
  'control-height-sm': '28px',
  'focus-ring-width': '2px',
  'focus-ring-offset': '2px',
} as const;

export type DesignTokenName = keyof typeof DESIGN_TOKENS;
